/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jxta;

import java.io.File;
import java.io.FilenameFilter;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.jxta.share.ContentAdvertisement;

/**
 *
 * @author Robson Gomes
 */
public class Principal extends javax.swing.JFrame {
    
    static Principal principal;
    static String Caminho = null;
    static String CheckSumOriginal = "desconhecido";
    static String NomeMeuArquivo = null;
    static IniciarJXTA Conexao = null;
    static ListaDePeers ListaPeers = null;
    static GrupoCompartilhamento IniciarCompartilhamento = null;
    static PesquisarArquivo IniciarPesquisa = null;
    static DownloadArquivo Download = null;
    static CalculoCheckSum MeuCheckSum = new CalculoCheckSum();
    static ContentAdvertisement[] ConteudoCompartilhado = null;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        InicializarInterface();
    }
    
    public void InicializarInterface() {
        try {
            setResizable(false);
            setLocationRelativeTo(null);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao iniciar a aplicação: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TermosDeUso = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAceitarTermo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneArquivosCompartilhados = new javax.swing.JScrollPane();
        meusArquivosCompartilhados = new javax.swing.JTable();
        btnAtualizarMeusArquivos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneArquivosCompartilhados1 = new javax.swing.JScrollPane();
        JTableArquivosCompartilhados = new javax.swing.JTable();
        txtNomeArquivo = new javax.swing.JTextField();
        btnPesquisarArquivo = new javax.swing.JButton();
        btnPararPesquisa = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        jPanelSatusDownload = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelProgresso = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        minhaBarraDeProgresso = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        btnPesquisarPeers = new javax.swing.JButton();
        jScrollPanePeers = new javax.swing.JScrollPane();
        ListaDePeers = new javax.swing.JList();
        btnPararPesquisaPeers = new javax.swing.JButton();

        TermosDeUso.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        TermosDeUso.setTitle("Termos de uso - JArticles");
        TermosDeUso.setAlwaysOnTop(true);
        TermosDeUso.setMinimumSize(new java.awt.Dimension(790, 540));
        TermosDeUso.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        TermosDeUso.setPreferredSize(new java.awt.Dimension(790, 540));
        TermosDeUso.setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/fundo-jarticles.png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("VINCULAÇÃO\n1 – O usuário ficará legalmente vinculado aos presentes termos de uso ao clicar na opção\nACEITAR.\n\nLICENÇA DE USO\n2 – Em decorrência da aceitação dos presentes Termos de Uso, o JArticles concede  ao usuário\no direito de uso GRATUTO, NÃO EXCLUSIVO, NÃO COMERCIAL para acesso download e \ncompartilhamento de e-books no sistema.\n3 – A licença de uso é concedida por prazo INDETERMINADO, podendo ser revogado pela \nequipe de desenvolvimento a qualquer momento, independente de aviso prévio  ao Usuário.\n4 – Através da utilização do JArticles licenciado a título GRATUITO, o Usuário poderá \nacessar os artigos digitais e realizar o download e compartilhamento de novos arquivos.\n\nDIREITOS DE PROPRIEDADE INTELECTUAL\n5 – No caso de qualquer violação de direitos de propriedade intelectual, configura-se à\neventual violação, sujeitando o USUÁRIO às sanções previstas na legislação aplicável,\nem especial o pagamento de indenização pela violação de direitos autorais.\n\nDISPOSIÇÕES GERAIS\n6 – Todas as senhas de acesso fornecidas ao USUÁRIO, ou por ele implantadas, são  \npessoais e intrasferíveis, de uso exclusivo do USUÁRIO, que assume integral\nresponsabilidade pela sua guarda e sigilo, bem como pelo uso indevido por terceiros.");
        jScrollPane1.setViewportView(jTextArea1);

        btnAceitarTermo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-aceitar-termos.png"))); // NOI18N
        btnAceitarTermo.setText("Concordo com os termos de uso (:");
        btnAceitarTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarTermoActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-cancelar.png"))); // NOI18N
        btnSair.setText("Não concordo");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TermosDeUsoLayout = new javax.swing.GroupLayout(TermosDeUso.getContentPane());
        TermosDeUso.getContentPane().setLayout(TermosDeUsoLayout);
        TermosDeUsoLayout.setHorizontalGroup(
            TermosDeUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermosDeUsoLayout.createSequentialGroup()
                .addGroup(TermosDeUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TermosDeUsoLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(TermosDeUsoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TermosDeUsoLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(btnAceitarTermo)
                        .addGap(10, 10, 10)
                        .addComponent(btnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TermosDeUsoLayout.setVerticalGroup(
            TermosDeUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermosDeUsoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TermosDeUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceitarTermo)
                    .addComponent(btnSair))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JArticles");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Meus arquivos compartilhados"));

        meusArquivosCompartilhados.setAutoCreateRowSorter(true);
        meusArquivosCompartilhados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome do Arquivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        meusArquivosCompartilhados.setToolTipText("Arquivos encontrados");
        jScrollPaneArquivosCompartilhados.setViewportView(meusArquivosCompartilhados);

        btnAtualizarMeusArquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-atualizar.png"))); // NOI18N
        btnAtualizarMeusArquivos.setText("Atualizar");
        btnAtualizarMeusArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarMeusArquivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneArquivosCompartilhados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnAtualizarMeusArquivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneArquivosCompartilhados, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarMeusArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        JTableArquivosCompartilhados.setAutoCreateRowSorter(true);
        JTableArquivosCompartilhados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome do Arquivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableArquivosCompartilhados.setToolTipText("Arquivos encontrados");
        jScrollPaneArquivosCompartilhados1.setViewportView(JTableArquivosCompartilhados);

        btnPesquisarArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-conexao.png"))); // NOI18N
        btnPesquisarArquivo.setText("Pesquisar");
        btnPesquisarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarArquivoActionPerformed(evt);
            }
        });

        btnPararPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-stop.png"))); // NOI18N
        btnPararPesquisa.setText("Parar");
        btnPararPesquisa.setEnabled(false);
        btnPararPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararPesquisaActionPerformed(evt);
            }
        });

        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/download.png"))); // NOI18N
        btnDownload.setText("Download");
        btnDownload.setToolTipText("Download do arquivo selecionado");
        btnDownload.setEnabled(false);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        jPanelSatusDownload.setBorder(javax.swing.BorderFactory.createTitledBorder("Status do download"));

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStatus.setText("Status:");

        jLabelProgresso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProgresso.setText("Progresso");

        lblStatus.setForeground(new java.awt.Color(0, 0, 153));
        lblStatus.setText("Aguardando...");
        lblStatus.setToolTipText("Status do download");

        minhaBarraDeProgresso.setToolTipText("Progresso do download");
        minhaBarraDeProgresso.setStringPainted(true);

        javax.swing.GroupLayout jPanelSatusDownloadLayout = new javax.swing.GroupLayout(jPanelSatusDownload);
        jPanelSatusDownload.setLayout(jPanelSatusDownloadLayout);
        jPanelSatusDownloadLayout.setHorizontalGroup(
            jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSatusDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minhaBarraDeProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSatusDownloadLayout.setVerticalGroup(
            jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSatusDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSatusDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProgresso)
                    .addComponent(minhaBarraDeProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPaneArquivosCompartilhados1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnPesquisarArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPararPesquisa))
                    .addComponent(jPanelSatusDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarArquivo)
                    .addComponent(btnPararPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneArquivosCompartilhados1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSatusDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Peers"));

        btnPesquisarPeers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-conexao.png"))); // NOI18N
        btnPesquisarPeers.setText("Procurar Peers");
        btnPesquisarPeers.setRequestFocusEnabled(false);
        btnPesquisarPeers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPeersActionPerformed(evt);
            }
        });

        ListaDePeers.setToolTipText("Lista de peers");
        jScrollPanePeers.setViewportView(ListaDePeers);

        btnPararPesquisaPeers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jxta/icons/icon-stop.png"))); // NOI18N
        btnPararPesquisaPeers.setText("Parar Procura");
        btnPararPesquisaPeers.setEnabled(false);
        btnPararPesquisaPeers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararPesquisaPeersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePeers)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(btnPesquisarPeers, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPararPesquisaPeers, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPanePeers, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarPeers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPararPesquisaPeers))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        try {
            int rowNum;
            if ((rowNum = JTableArquivosCompartilhados.getSelectedRow()) != -1) {
                if (ConteudoCompartilhado != null) {
                    //CheckSumOriginal = JTableArquivosCompartilhados.getValueAt(rowNum, 2).toString();
                    NomeMeuArquivo = JTableArquivosCompartilhados.getValueAt(rowNum, 0).toString();
                    //lblNomeArquivo.setText(NomeMeuArquivo);
                    lblStatus.setText("Baixando arquivo...");
                    File destinoArquivo = new File(Caminho + File.separator + NomeMeuArquivo);
                    Download = new DownloadArquivo(Conexao.getGrupoSistemaDistribuidos(), ConteudoCompartilhado[rowNum], destinoArquivo, this.minhaBarraDeProgresso);
                    Download.start();
                    //btnCancelarDownload.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, selecione o arquivo desejado e depois clique em Download!", "JArticles", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAceitarTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarTermoActionPerformed
        // TODO add your handling code here:
        this.TermosDeUso.setVisible(false);
        principal.setVisible(true);  
    }//GEN-LAST:event_btnAceitarTermoActionPerformed

    private void btnPesquisarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarArquivoActionPerformed
        // TODO add your handling code here:
        try {
            String nomeArquivo = this.txtNomeArquivo.getText();
            if (!"".equals(nomeArquivo)) {
                if (nomeArquivo.contains(".")) {
                    nomeArquivo = nomeArquivo.substring(0, nomeArquivo.lastIndexOf('.'));
                }
                IniciarPesquisa = new PesquisarArquivo(Conexao.getGrupoSistemaDistribuidos(), nomeArquivo + ".pdf", this.JTableArquivosCompartilhados);
                IniciarPesquisa.start();
                btnPesquisarArquivo.setEnabled(false);
                btnPararPesquisa.setEnabled(true);
                btnDownload.setEnabled(false);
                txtNomeArquivo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Informe um valor para pesquisa!", "JArticles", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarArquivoActionPerformed

    private void btnPesquisarPeersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPeersActionPerformed
        // TODO add your handling code here:
        try {
            ListaPeers.start();
            btnPesquisarPeers.setEnabled(false);
            btnPararPesquisaPeers.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarPeersActionPerformed

    private void btnAtualizarMeusArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarMeusArquivosActionPerformed
        // TODO add your handling code here:
        try {
            File diretorio = new File(Caminho);
            File[] listaArquivos = diretorio.listFiles(new FilenameFilter() {
                @Override
                public boolean accept(File dir, String filename) {
                    return filename.endsWith(".pdf");
                }
            });
            String[] tituloTabela = {"Nome do Arquivo"};
            int qtArquivos = 0;
            for (File listaArquivo : listaArquivos) {
                if (listaArquivo.isFile()) {
                    qtArquivos++;
                }
            }
            DefaultTableModel TableModel = new DefaultTableModel(tituloTabela, qtArquivos) {
                @Override
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                    return false;
                }
            };
            meusArquivosCompartilhados.setModel(TableModel);
            int j = 0;
            for (File listaArquivo : listaArquivos) {
                if (listaArquivo.isFile()) {
                    meusArquivosCompartilhados.setValueAt(listaArquivo.getName(), j, 0);
                    //meusArquivosCompartilhados.setValueAt(listaArquivo.length(), j, 1);
                    //meusArquivosCompartilhados.setValueAt(MeuCheckSum.getSumArquivo(listaArquivo), j, 2);
                    j++;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarMeusArquivosActionPerformed

    private void btnPararPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararPesquisaActionPerformed
        // TODO add your handling code here:
        try {
            IniciarPesquisa.killThread();
            ConteudoCompartilhado = ListaRequisicao.resultadoPesquisa;
            IniciarPesquisa = null;
            btnPesquisarArquivo.setEnabled(true);
            btnDownload.setEnabled(true);
            btnPararPesquisa.setEnabled(false);
            txtNomeArquivo.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPararPesquisaActionPerformed

    private void btnPararPesquisaPeersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararPesquisaPeersActionPerformed
        // TODO add your handling code here:
        try {
            btnPesquisarPeers.setEnabled(true);
            ListaPeers.setFimDaPesquisa(true);
            ListaPeers = new ListaDePeers(Conexao.getGrupoSistemaDistribuidos(), this.ListaDePeers);
            btnPararPesquisaPeers.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage(), "JArticles", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPararPesquisaPeersActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        principal = new Principal();                              
        principal.TermosDeUso.setLocationRelativeTo(null);
        principal.TermosDeUso.setVisible(true);
        PrimeiroCheckIn verificar = new PrimeiroCheckIn();
        if (verificar.ehPrimeiraVez()) {
            JOptionPane.showMessageDialog(null, "Selecione sua pasta de compartilhamento", "JArticles", JOptionPane.INFORMATION_MESSAGE);
            verificar.pesquisarArquivoConfiguracao();
            Caminho = verificar.getCaminhoCompartilhado();
        } else {
            verificar.pesquisarArquivoConfiguracao();
            Caminho = verificar.getCaminhoCompartilhado();
        }
        Conexao = new IniciarJXTA();
        ListaPeers = new ListaDePeers(Conexao.getGrupoSistemaDistribuidos(), principal.ListaDePeers);
        IniciarCompartilhamento = new GrupoCompartilhamento(Conexao.getGrupoSistemaDistribuidos(), new File(Caminho));
        IniciarCompartilhamento.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTableArquivosCompartilhados;
    public javax.swing.JList ListaDePeers;
    private javax.swing.JDialog TermosDeUso;
    private javax.swing.JButton btnAceitarTermo;
    private javax.swing.JButton btnAtualizarMeusArquivos;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnPararPesquisa;
    private javax.swing.JButton btnPararPesquisaPeers;
    private javax.swing.JButton btnPesquisarArquivo;
    private javax.swing.JButton btnPesquisarPeers;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelProgresso;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSatusDownload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneArquivosCompartilhados;
    private javax.swing.JScrollPane jScrollPaneArquivosCompartilhados1;
    private javax.swing.JScrollPane jScrollPanePeers;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblStatus;
    public javax.swing.JTable meusArquivosCompartilhados;
    public javax.swing.JProgressBar minhaBarraDeProgresso;
    private javax.swing.JTextField txtNomeArquivo;
    // End of variables declaration//GEN-END:variables
}
